### ISSUE TITLE
Why not use SQLite2XL?

### ISSUE THREAD

**Issue by searchy2** [li-yu/SQLiteToExcel#4]
There is another library that has the same features as this library. 
https://github.com/androidmads/SQLite2XL

This library has 4 dependencies and 22981! methods. SQLite2XL has no dependencies and only 127 methods. Why use this library instead of SQLite2XL?

**Comment by li-yu** [comment]
Hi @searchy2,  thanks for your advising.

Why has the same features?
First of all,  SQLite2XL is based on SQLiteToExcel，you will see “Created by liyu on 2015-9-8” in his java [file](https://github.com/androidmads/SQLite2XL/blob/master/library/src/main/java/com/ajts/androidmads/library/SQLiteToExcel.java).

SQLite2XL has no dependencies, because it has a [jar dependence](https://github.com/androidmads/SQLite2XL/blob/master/library/libs/poi.jar). Did you count the number of methods？
SQLiteToExcel use gradle dependencies "compile 'org.apache.poi:poi:3.16'" and "compile 'com.android.support:support-annotations:25.3.0'",  just for convenience. 

No one wants to instead of it, and we all just want to make a good library.

**Comment by searchy2** [comment]
:man_facepalming: So the library I am suggesting is actually based off of your library. Wow! Thank you for explaining and making this library. I just made such a stupid suggestion :P

**Comment by li-yu** [comment]
@searchy2 :smile:Hahaha...., if you have any questions and suggestions, please contact to me, let us improve this library together！:blush:
